networks:
 holiday-homes:

services:
  nginx:
    image: nelwhix/holidayhomes-nginx
    ports:
      - "8081:80"
    networks:
      - holiday-homes
  php:
    image: nelwhix/holidayhomes-php
    ports:
      - "9000:9000"
    networks:
      - holiday-homes